### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [4]:
a = torch.zeros(2, 1, 2, 1, 2)
b = torch.unsqueeze(a,0)
c = torch.squeeze(a,1)

print('The original size:', a.size())
print('After unsqueeze:', b.size())
print('After squeeze:', c.size())

The original size: torch.Size([2, 1, 2, 1, 2])
After unsqueeze: torch.Size([1, 2, 1, 2, 1, 2])
After squeeze: torch.Size([2, 2, 1, 2])


### Function 3 - tensor.transpose() / tensor.permute()

In [5]:
a = torch.randn(2, 3, 5)
b = torch.transpose(a, 0, 1)
c = a.permute(2, 0, 1)

print('The original tensor:')
print(a)
print('After transpose:')
print(b)
print('After permute:')
print(c)

The original tensor:
tensor([[[-0.0399, -0.4841, -0.0524, -0.9928, -0.9359],
         [ 0.8842, -0.6597, -0.4156, -2.8070, -0.0656],
         [-1.0956,  1.5318, -0.3724, -0.0823, -1.1086]],

        [[-0.4094, -1.4611,  0.9558, -1.4756, -0.1220],
         [-0.0186,  0.2023, -0.2720, -0.6893, -1.7591],
         [-0.0820, -0.0159,  0.5479,  0.5539,  1.8551]]])
After transpose:
tensor([[[-0.0399, -0.4841, -0.0524, -0.9928, -0.9359],
         [-0.4094, -1.4611,  0.9558, -1.4756, -0.1220]],

        [[ 0.8842, -0.6597, -0.4156, -2.8070, -0.0656],
         [-0.0186,  0.2023, -0.2720, -0.6893, -1.7591]],

        [[-1.0956,  1.5318, -0.3724, -0.0823, -1.1086],
         [-0.0820, -0.0159,  0.5479,  0.5539,  1.8551]]])
After permute:
tensor([[[-0.0399,  0.8842, -1.0956],
         [-0.4094, -0.0186, -0.0820]],

        [[-0.4841, -0.6597,  1.5318],
         [-1.4611,  0.2023, -0.0159]],

        [[-0.0524, -0.4156, -0.3724],
         [ 0.9558, -0.2720,  0.5479]],

        [[-0.9928, -2.8070, -0.

### Function 4 - torch.reshape() / tensor.view()

In [6]:
a = torch.randn(2, 3, 5)
b = torch.reshape(a, (6, 5))
c = a.view(6,5)

print('The original tensor:')
print(a)
print('After reshape:')
print(b)
print('tensor.view:')
print(c)

The original tensor:
tensor([[[-0.0950, -1.7016, -0.9661,  0.7810,  2.3840],
         [ 1.2429,  0.0808, -0.3091, -1.4202, -1.7802],
         [-0.0148, -0.8266,  0.2723,  0.6741,  1.2850]],

        [[-0.5209,  0.4675,  1.2773, -0.4544, -1.0143],
         [ 0.5665, -0.5854,  0.4535,  1.6691,  0.6988],
         [-0.2682, -0.7600, -0.3995, -0.7941,  0.2428]]])
After reshape:
tensor([[-0.0950, -1.7016, -0.9661,  0.7810,  2.3840],
        [ 1.2429,  0.0808, -0.3091, -1.4202, -1.7802],
        [-0.0148, -0.8266,  0.2723,  0.6741,  1.2850],
        [-0.5209,  0.4675,  1.2773, -0.4544, -1.0143],
        [ 0.5665, -0.5854,  0.4535,  1.6691,  0.6988],
        [-0.2682, -0.7600, -0.3995, -0.7941,  0.2428]])
tensor.view:
tensor([[-0.0950, -1.7016, -0.9661,  0.7810,  2.3840],
        [ 1.2429,  0.0808, -0.3091, -1.4202, -1.7802],
        [-0.0148, -0.8266,  0.2723,  0.6741,  1.2850],
        [-0.5209,  0.4675,  1.2773, -0.4544, -1.0143],
        [ 0.5665, -0.5854,  0.4535,  1.6691,  0.6988],
     